export const SET_USER = 'SET_USER';
export const SET_IS_CONNECTED = 'SET_IS_CONNECTED';

export const ADD_SAVE_BOX_DATA = 'ADD_SAVE_BOX_DATA';
export const UPDATE_SAVE_BOX_DATA_ITEM = 'UPDATE_SAVE_BOX_DATA_ITEM';